default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: user_r2_development
test:
  <<: *default
  database: user_r2_test

production:
  <<: *default
  database: user_r2_production
  username: user_r2
  password: <%= ENV["DATABASE_PASSWORD"] %>
